modLoader="javafml" #mandatory

license="All rights reserved to Team Draco."

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="aintgotrythm" #mandatory

version="1.16.4-1.0.0" #mandatory

displayName="Ain't Got Rythm Mod" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Coda, Mr. Esuoh, Ninni, Dino/Tazz" #optional

authors="Coda, Mr. Esuoh, Ninni, Dino/Tazz" #optional

description='''Music Disc Mod'''
